[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "^1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "^1.2.0"

[[constraint]]
name = "github.com/kshvakov/clickhouse"
version = "^v1.3.11"